version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "npm"
    directory: "/examples/node"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "gomod"
    directory: "/examples/go"
    schedule:
      interval: "weekly"
      day: "monday"

  - package-ecosystem: "cargo"
    directory: "/examples/rust"
    schedule:
      interval: "weekly"
      day: "monday"
